//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterBPMGDCLI.Resources.CLICommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddProject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddProject() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterBPMGDCLI.Resources.CLICommands.AddProject", typeof(AddProject).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new project.
        /// </summary>
        internal static string COMMAND_DESCRIPTION {
            get {
                return ResourceManager.GetString("COMMAND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project,pj,proj.
        /// </summary>
        internal static string COMMAND_NAME_ALIASES {
            get {
                return ResourceManager.GetString("COMMAND_NAME_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name could not be an empty string.
        /// </summary>
        internal static string ERROR_MEMBERCANNOTBEANEMPTYSTRING {
            get {
                return ResourceManager.GetString("ERROR_MEMBERCANNOTBEANEMPTYSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --song,-s.
        /// </summary>
        internal static string OPTION_INT32_ALIASES {
            get {
                return ResourceManager.GetString("OPTION_INT32_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the id for the initial song of the project.
        /// </summary>
        internal static string OPTION_INT32_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTION_INT32_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --name,-n.
        /// </summary>
        internal static string OPTION_STRING_ALIASES {
            get {
                return ResourceManager.GetString("OPTION_STRING_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name for the project.
        /// </summary>
        internal static string OPTION_STRING_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTION_STRING_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --offset,-o.
        /// </summary>
        internal static string OPTION_UINT64_ALIASES {
            get {
                return ResourceManager.GetString("OPTION_UINT64_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the offset for the initial song of the project.
        /// </summary>
        internal static string OPTION_UINT64_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTION_UINT64_DESCRIPTION", resourceCulture);
            }
        }
    }
}
