//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterBPMGDCLI.Resources.CLICommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SearchLevelsByNameCommand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchLevelsByNameCommand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterBPMGDCLI.Resources.CLICommands.SearchLevelsByNameCommand", typeof(SearchLevelsByNameCommand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches levels by name. Returns collection of levels that match the specified name..
        /// </summary>
        internal static string COMMAND_DESCRIPTION {
            get {
                return ResourceManager.GetString("COMMAND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchL,searchLevels,searchlevels,search-levels,search-l,searchl,srchl,srch-l,srchL.
        /// </summary>
        internal static string COMMAND_NAME_ALIASES {
            get {
                return ResourceManager.GetString("COMMAND_NAME_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No levels found.
        /// </summary>
        internal static string ERROR_MEMBERDOESNOTEXISTS {
            get {
                return ResourceManager.GetString("ERROR_MEMBERDOESNOTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --case,-c,--insensitive,--caseinsensitive,--caseInsensitive,--case-insensitive,-i,--ignoreCase,--ignorecase,--ignore-case.
        /// </summary>
        internal static string OPTION_BOOL_ALIASES {
            get {
                return ResourceManager.GetString("OPTION_BOOL_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether search should be case insensitive.
        /// </summary>
        internal static string OPTION_BOOL_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTION_BOOL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --name,-n.
        /// </summary>
        internal static string OPTION_NAME_ALIASES {
            get {
                return ResourceManager.GetString("OPTION_NAME_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of the levels.
        /// </summary>
        internal static string OPTION_NAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTION_NAME_DESCRIPTION", resourceCulture);
            }
        }
    }
}
