//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterBPMGDCLI.Resources.CLICommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StopCommand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StopCommand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterBPMGDCLI.Resources.CLICommands.StopCommand", typeof(StopCommand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the continuous mode.
        /// </summary>
        internal static string COMMAND_DESCRIPTION {
            get {
                return ResourceManager.GetString("COMMAND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit,quit,:q,stop.
        /// </summary>
        internal static string COMMAND_NAME_ALIASES {
            get {
                return ResourceManager.GetString("COMMAND_NAME_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup file is already deleted.
        /// </summary>
        internal static string ERROR_MEMBERDOESNOTEXISTS {
            get {
                return ResourceManager.GetString("ERROR_MEMBERDOESNOTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local files are already deleted.
        /// </summary>
        internal static string ERROR_MEMBERDOESNOTEXISTS1 {
            get {
                return ResourceManager.GetString("ERROR_MEMBERDOESNOTEXISTS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup files are already deleted.
        /// </summary>
        internal static string ERROR_MEMBERDOESNOTEXISTS2 {
            get {
                return ResourceManager.GetString("ERROR_MEMBERDOESNOTEXISTS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the continuous mode....
        /// </summary>
        internal static string MESSAGE_SUCCESS {
            get {
                return ResourceManager.GetString("MESSAGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --delete-local-files,--delete-localFiles,--deleteLocalFiles,--local,--dl,-l.
        /// </summary>
        internal static string OPTION_BOOLEAN_1_ALIASES {
            get {
                return ResourceManager.GetString("OPTION_BOOLEAN_1_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes local files. (Not recommended).
        /// </summary>
        internal static string OPTION_BOOLEAN_1_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTION_BOOLEAN_1_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --delete-backup-files,--delete-backupFiles,--deleteBackupFiles,--backup,--db,-b.
        /// </summary>
        internal static string OPTION_BOOLEAN_2_ALIASES {
            get {
                return ResourceManager.GetString("OPTION_BOOLEAN_2_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes backup files. (Not recommended).
        /// </summary>
        internal static string OPTION_BOOLEAN_2_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTION_BOOLEAN_2_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --delete-startup-file,--delete-startupFile,--deleteStartupFile,--startup,--ds,-s.
        /// </summary>
        internal static string OPTION_BOOLEAN_ALIASES {
            get {
                return ResourceManager.GetString("OPTION_BOOLEAN_ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes startup file. (Not recommended).
        /// </summary>
        internal static string OPTION_BOOLEAN_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTION_BOOLEAN_DESCRIPTION", resourceCulture);
            }
        }
    }
}
